{"name": "Вход с неверными данными → 401", "status": "passed", "steps": [{"name": "Login user", "status": "passed", "parameters": [{"name": "email", "value": "'wrong@example.com'"}, {"name": "password", "value": "'Password123!'"}], "start": 1750948445420, "stop": 1750948445465}], "parameters": [{"name": "email", "value": "'wrong@example.com'"}, {"name": "password", "value": "'Password123!'"}], "start": 1750948445420, "stop": 1750948445465, "uuid": "914a5cea-9d70-480a-b6e5-89f03a580cf6", "historyId": "fdd925a91822a3ee891a4144b582bfd4", "testCaseId": "5da0defd295c5b73991b1ce5dbbe7dd0", "fullName": "tests.test_login.TestLogin#test_login_invalid", "labels": [{"name": "story", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47CL42P"}, {"name": "thread", "value": "22616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}